#!/bin/sh
# Ensure build src directories exist
mkdir -p .pio/build/*/src 2>/dev/null || true
exec "/Users/pavelmasyukov/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-g++" "$@"
